server:
  host: 0.0.0.0
  port: 8000
database:
  engine: postgres
  host: localhost
  user: postgres
  password: "!Graid363521!"
  db_name: graduation_project_db
paths:
  data:
    linux: /var/gpks/
    windows: %APPDATA%/gpks/
publish:
  docs:
    path: docs